version: '3.8'

services:
  codebase-mcp:
    build: .
    container_name: codebase-mcp
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - .:/app
    depends_on:
      - qdrant
    networks:
      - mcp_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file:
      - .env
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_PORT:-6333}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_GRPC_PORT:-6334}
    restart: unless-stopped
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local